function bg140Form() {
    var html = '<div id="panel1" class="col-md-12">'
            + '<section class="panel">'
                + '<div class="panel-body">'
                    + '<table class="table table-bordered table-striped mb-none treetable" id="example">'
                        + '<thead>'
                            + '<tr>'
                                + '<th rowspan="3" class="text-center" style="vertical-align: middle;">ลำดับ</th>'
                                + '<th rowspan="3" class="text-center" style="vertical-align: middle;">ชื่อตำแหน่ง</th>'
                                + '<th colspan="5" class="text-center" style="vertical-align: middle;">อัตราเดิม (ตามบัญชีถือจ่าย ณ ต.ค.57)</th>'
                                + '<th rowspan="3" class="text-center" style="vertical-align: middle;">คำชี้แจง</th>'
                            + '</tr>'
                            + '<tr>'
                                + '<th rowspan="2" class="text-center" style="vertical-align: middle;">ระดับ</th>'
                                + '<th rowspan="2" class="text-center" style="vertical-align: middle;">อัตราเงินเดือน</th>'
                                + '<th colspan="2" class="text-center" style="vertical-align: middle;">จำนวนอัตรา</th>'
                                + '<th rowspan="2" class="text-center" style="vertical-align: middle;">จำนวนเงินทั้งปี</th>'
                            + '</tr>'
                            + '<tr>'
                                + '<th class="text-center" style="vertical-align: middle;">มีคนครอง</th>'
                                + '<th class="text-center" style="vertical-align: middle;">อัตราว่าง</th>'
                            + '</tr>'
                        + '</thead>'
                        + '<tbody>'
                            + '<tr data-tt-id="1">'
                                + '<td><a href="#" class="popup">Trident</a></td>'
                                + '<td>Internet Explorer 4.0</td>'
                                + '<td>Win 95+</td>'
                                + '<td class="center">4</td>'
                                + '<td class="center">X</td>'
                            + '</tr>'
                            + '<tr data-tt-id="2" data-tt-parent-id="1">'
                                + '<td>Trident2</td>'
                                + '<td>Internet Explorer 5.0</td>'
                                + '<td>Win 95+</td>'
                                + '<td class="center">5</td>'
                                + '<td class="center">C</td>'
                            + '</tr>'
                            + '<tr data-tt-id="3" data-tt-parent-id="1">'
                                + '<td>Trident2</td>'
                                + '<td>Internet Explorer 5.0</td>'
                                + '<td>Win 95+</td>'
                                + '<td class="center">5</td>'
                                + '<td class="center">C</td>'
                            + '</tr>'
                        + '</tbody>'
                    + '</table>'
                + '</div>'
            + '</section>'
        + '</div>'

        + '<div id="panel2" aria-labelledby="bidderLabel" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">'
            + '<div class="modal-dialog">'
                + '<div class="modal-content">'
                    + '<div class="modal-header">'
                        + '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>'
                        + '<h4 class="modal-title" id="myModalLabel">คำของบประมาณเงินเดือน</h4>'
                    + '</div>'
                    + '<div class="modal-body">'
                        + '<form onsubmit="return false;">'
                            + '<div class="form-group">'
                                + '<label class="col-md-12 control-label" for="xxx">ชื่อตำแหน่ง</label>'
                                + '<div class="col-md-12">'
                                    + '<input type="text" id="listBudgetPlan" name="listBudgetPlan" class="form-control input-sm" required>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<label class="col-md-12 control-label" for="xxx">ระดับ</label>'
                                + '<div class="col-md-12">'
                                    + '<input type="text" id="listBudgetPlan" name="listBudgetPlan" class="form-control input-sm" required>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<label class="col-md-12 control-label" for="xxx">อัตราเงินเดือน</label>'
                                + '<div class="col-md-12">'
                                    + '<input type="text" id="listBudgetPlan" name="listBudgetPlan" class="form-control input-sm" required>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<label class="col-md-12 control-label" for="xxx">จำนวนอัตรา</label>'
                                + '<div class="col-md-12">'
                                        + '<label class="col-md-3 control-label text-right" for="xxx">มีคนครอง</label>'
                                        + '<div class="col-md-3">'
                                            + '<input type="text" id="listBudgetPlan" name="listBudgetPlan" class="form-control input-sm" required>'
                                        + '</div>'

                                        + '<label class="col-md-3 control-label text-right" for="xxx">อัตราว่าง</label>'
                                        + '<div class="col-md-3">'
                                            + '<input type="text" id="listBudgetPlan" name="listBudgetPlan" class="form-control input-sm" required>'
                                        + '</div>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<label class="col-md-12 control-label" for="xxx">จำนวนเงินทั้งปี</label>'
                                + '<div class="col-md-12">'
                                    + '<input type="text" id="listBudgetPlan" name="listBudgetPlan" class="form-control input-sm" required>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<label class="col-md-12 control-label" for="xxx">คำชี้แจง</label>'
                                + '<div class="col-md-12">'
                                    + '<textarea id="listBudgetPlan" name="listBudgetPlan" class="form-control input-sm" required></textarea>'
                                + '</div>'
                            + '</div>'
                        + '</form>'
                    + '</div>'
                    + '<div class="modal-footer">'
                        + '<button type="button" class="btn btn-default" data-dismiss="modal">ยกเลิก</button>'
                        + '<button type="button" id="confirmChange" class="btn btn-primary" data-dismiss="modal">ยืนยัน</button>'
                    + '</div>'
                + '</div>'
            + '</div>'
        + '</div>';

    $("#formBudget").html(html);

    $("#example").treetable({
        expandable: true
    });

    $("a.popup").unbind().click(function(evt){
        $("#panel2").modal("show");
    });

    $("a.close").unbind().click(function(){
        $("#panel2").hide();
        $("#panel1").removeClass("col-md-7").addClass("col-md-12");
    })
}

