function bg145Form(){
    var html = '<div class="col-md-12 text-center">'
        + '<h4>'
            + 'แบบรายละเอียดคำของบประมาณเงินอุดหนุนเป็นค่าครุภัณฑ์ ค่าที่ดิน/สิ่งก่อสร้าง (ง.145)'
        + '</h4>'
    + '</div>'

    + '<form>'
        + '<div class="form-group">'
            + '<div class="col-md-4">'
                + '<label class="col-md-4 control-label text-right" for="xxx">แผนงาน</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-4">'
                + '<label class="col-md-4 control-label text-right" for="xxx">ผลผลิต</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-4">'
                + '<label class="col-md-4 control-label text-right" for="xxx">หน่วยงาน</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'

            + '<div class="col-md-8 text-right">'
                + '<button class="btn btn-success"><i class="fa fa-save"></i> บันทึก</button>&nbsp;'
                + '<button class="btn btn-default"><i class="fa fa-trash"></i> ล้างข้อมูล</button>'
            + '</div>'
        + '</div>'
    + '</form>'

    + '<div class="col-md-12" style="margin-top: 20px;">'
        + '<div class="panel-group" id="accordion">'
            + '<div class="panel panel-default">'
                + '<div class="panel-heading">'
                    + '<h4 class="panel-title">'
                        + '<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse1One">'
                            + '<i class="fa fa-plus-circle"></i> เพิ่มรายการ'
                        + '</a>'
                    + '</h4>'
                + '</div>'
                + '<div id="collapse1One" class="accordion-body collapse in">'
                    + '<div class="panel-body">'
                        + '<form>'
                            + '<div class="form-group">'
                                + '<div class="col-md-9">'
                                    + '<label class="col-md-4 control-label text-right" for="xxx">หมวดรายจ่าย</label>'
                                    + '<div class="col-md-8">'
                                        + '<select id="" name="" class="form-control input-sm" required>'
                                        + '</select>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<div class="col-md-9">'
                                    + '<label class="col-md-4 control-label text-right" for="xxx">รายการและรายละเอียดประกอบ</label>'
                                    + '<div class="col-md-8">'
                                        + '<textarea id="" name="" class="form-control input-sm">'
                                        + '</textarea>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<div class="col-md-9">'
                                    + '<label class="col-md-4 control-label text-right" for="xxx">จำนวนหน่วย</label>'
                                    + '<div class="col-md-8">'
                                        + '<select id="" name="" class="form-control input-sm" required>'
                                        + '</select>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<div class="col-md-9">'
                                    + '<label class="col-md-4 control-label text-right" for="xxx">ราคาต่อหน่วย</label>'
                                    + '<div class="col-md-8">'
                                        + '<select id="" name="" class="form-control input-sm" required>'
                                        + '</select>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<div class="col-md-9">'
                                    + '<label class="col-md-4 control-label text-right" for="xxx">รวมเงิน</label>'
                                    + '<div class="col-md-8">'
                                        + '<select id="" name="" class="form-control input-sm" required>'
                                        + '</select>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<div class="col-md-9">'
                                    + '<div class="col-md-12" style="margin: 3px 0;">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx">คำชี้แจง</label>'
                                        + '<div class="col-md-8">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx">ความต้องการทั้งสิ้น</label>'
                                            + '<div class="col-md-8">'
                                                + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                            + '</div>'
                                        + '</div>'
                                    + '</div>'
                                    + '<div class="col-md-12" style="margin: 3px 0;">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                        + '<div class="col-md-8">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx">มีอยู่แล้ว</label>'
                                            + '<div class="col-md-8">'
                                                + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                            + '</div>'
                                        + '</div>'
                                    + '</div>'
                                    + '<div class="col-md-12" style="margin: 3px 0;">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                        + '<div class="col-md-8">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx">ใช้การได้</label>'
                                            + '<div class="col-md-8">'
                                                + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                            + '</div>'
                                        + '</div>'
                                    + '</div>'
                                    + '<div class="col-md-12" style="margin: 3px 0;">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                        + '<div class="col-md-8">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx">ใช้การไม่ได้</label>'
                                            + '<div class="col-md-8">'
                                                + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                            + '</div>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'

                            + '<div class="form-group">'
                                + '<div class="col-md-9">'
                                    + '<label class="col-md-4 control-label text-right" for="xxx">เหตุผลความจำเป็น</label>'
                                    + '<div class="col-md-8">'
                                        + '<textarea id="" name="" class="form-control input-sm">'
                                        + '</textarea>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'
                        + '</form>'
                    + '</div>'
                + '</div>'
            + '</div>'
        + '</div>'
    + '</div>'

    + '<div id="bidderTable" class="col-md-12">'
        + '<table id="table" class="table table-bordered table-striped table-condensed mb-none">'
            + '<thead>'
                + '<tr>'
                    + '<th class="text-center" rowspan="3" style="vertical-align: middle;">ลำดับที่</th>'
                    + '<th class="text-center" rowspan="3" style="vertical-align: middle;">หมวดรายจ่ายรายการและรายละเอียดประกอบ</th>'
                    + '<th class="text-center" rowspan="3" style="vertical-align: middle;">จำนวนหน่วย</th>'
                    + '<th class="text-center" rowspan="3" style="vertical-align: middle;">ราคาต่อหน่วย</th>'
                    + '<th class="text-center" rowspan="3" style="vertical-align: middle;">รวมเงิน</th>'
                    + '<th class="text-center" colspan="3">คำชี้แจง</th>'
                    + '<th class="text-center" rowspan="3" style="vertical-align: middle;">เหตุผลความจำเป็น</th>'
                + '</tr>'
                + '<tr>'
                    + '<th class="text-center" rowspan="2" style="vertical-align: middle;">ความต้องการทั้งสิ้น</th>'
                    + '<th class="text-center" colspan="2">มีอยู่แล้ว</th>'
                + '</tr>'
                + '<tr>'
                    + '<th class="text-center">ใช้การได้</th>'
                    + '<th class="text-center">ใช้การไม่ได้</th>'
                + '</tr>'

                + '<tr>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center">รวมทั้งสิ้น</th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                + '</tr>'
            + '</thead>'
            + '<tbody id="bidderBody">'
                + '<tr>'
                    + '<td colspan="9" class="text-center">-</td>'
                + '</tr>'
            + '</tbody>'
        + '</table>'
    + '</div>';
    
    $("#formBudget").html(html);
    
     
}