function bg143Form(){
    var html = '<div class="col-md-12 text-center">'
        + '<h4>'
            + 'แบบรายละเอียดคำของบประมาณเงินอุดหนุนเป็นค่าใช้จ่ายดำเนินงาน (ค่าตอบแทน ใช้สอย และวัสดุ) (ง.143)'
        + '</h4>'
    + '</div>'

    + '<form>'
        + '<div class="form-group">'
            + '<div class="col-md-4">'
                + '<label class="col-md-4 control-label text-right" for="xxx">แผนงาน</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-4">'
                + '<label class="col-md-4 control-label text-right" for="xxx">ผลผลิต</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-4">'
                + '<label class="col-md-4 control-label text-right" for="xxx">หน่วยงาน</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'

            + '<div class="col-md-8 text-right">'
                + '<button class="btn btn-success"><i class="fa fa-save"></i> บันทึก</button>&nbsp;'
                + '<button class="btn btn-default"><i class="fa fa-trash"></i> ล้างข้อมูล</button>'
            + '</div>'
        + '</div>'
    + '</form>'

    + '<div class="col-md-12" style="margin-top: 20px;">'
        + '<div class="panel-group" id="accordion">'
            + '<div class="panel panel-default">'
                + '<div class="panel-heading">'
                    + '<h4 class="panel-title">'
                        + '<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse1One">'
                            + '<i class="fa fa-plus-circle"></i> เพิ่มรายการ'
                        + '</a>'
                    + '</h4>'
                    + '</div>'
                    + '<div id="collapse1One" class="accordion-body collapse in">'
                        + '<div class="panel-body">'
                            + '<form>'
                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx">หมวดรายจ่าย</label>'
                                        + '<div class="col-md-8">'
                                            + '<select id="" name="" class="form-control input-sm" required>'
                                            + '</select>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'

                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx">หมวดรายจ่าย - รายการ</label>'
                                        + '<div class="col-md-8">'
                                            + '<textarea id="" name="" class="form-control input-sm" required>'
                                            + '</textarea>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'

                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx">งบประมาณที่ได้รับการจัดสรรปีปัจจุบัน</label>'
                                        + '<div class="col-md-8">'
                                            + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'

                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx">คำของบประมาณปีงบประมาณที่ขอตั้ง</label>'
                                        + '<div class="col-md-8">'
                                            + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                         
                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx">คำชี้แจงเหตุผลสรุป</label>'
                                        + '<div class="col-md-8">'
                                            + '<textarea id="" name="" class="form-control input-sm">'
                                            + '</textarea>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                                
                                + '<div class="col-md-12 text-right">'
                                    + '<button class="btn btn-primary"><i class="fa fa-plus-circle"></i> เพิ่ม</button>&nbsp;'
                                    + '<button class="btn btn-default"><i class="fa fa-trash"></i> ยกเลิก</button>'
                                + '</div>'
                            + '</form>'
                        + '</div>'
                    + '</div>'
            + '</div>'
        + '</div>'
    + '</div>'

    + '<div id="bidderTable" class="col-md-12">'
        + '<table id="table" class="table table-bordered table-striped table-condensed mb-none">'
            + '<thead>'
                + '<tr>'
                    + '<th class="text-center">หมวดรายจ่าย-รายการ</th>'
                    + '<th class="text-center">งบประมาณที่ได้รับการจัดสรรปีปัจจุบัน (2558)</th>'
                    + '<th class="text-center">คำของบประมาณปีงบประมาณที่ขอตั้ง</th>'
                    + '<th class="text-center">คำชี้แจงเหตุผลสรุป</th>'
                + '</tr>'

                + '<tr>'
                    + '<th class="text-center">รวมทั้งสิ้น</th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                + '</tr>'
            + '</thead>'
            + '<tbody id="bidderBody">'
                + '<tr>'
                    + '<td colspan="4" class="text-center">-</td>'
                + '</tr>'
            + '</tbody>'
        + '</table>'
    + '</div>';
    
    $("#formBudget").html(html);
    
     
}