function bg144Form(){
    var html = '<div class="col-md-12 text-center">'
        + '<h4>'
            + 'แบบรายละเอียดคำของบประมาณเงินอุดหนุนเป็นค่าสาธารณูปโภค (ง.144)'
        + '</h4>'
    + '</div>'

    + '<form>'
        + '<div class="form-group">'
            + '<div class="col-md-4">'
                + '<label class="col-md-4 control-label text-right" for="xxx">แผนงาน</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-4">'
                + '<label class="col-md-4 control-label text-right" for="xxx">ผลผลิต</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-4">'
                + '<label class="col-md-4 control-label text-right" for="xxx">หน่วยงาน</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'

            + '<div class="col-md-8 text-right">'
                + '<button class="btn btn-success"><i class="fa fa-save"></i> บันทึก</button>&nbsp;'
                + '<button class="btn btn-default"><i class="fa fa-trash"></i> ล้างข้อมูล</button>'
            + '</div>'
        + '</div>'
    + '</form>'

    + '<div class="col-md-12" style="margin-top: 20px;">'
        + '<div class="panel-group" id="accordion">'
            + '<div class="panel panel-default">'
                + '<div class="panel-heading">'
                    + '<h4 class="panel-title">'
                        + '<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse1One">'
                            + '<i class="fa fa-plus-circle"></i> เพิ่มรายการ'
                        + '</a>'
                    + '</h4>'
                    + '</div>'
                    + '<div id="collapse1One" class="accordion-body collapse in">'
                        + '<div class="panel-body">'
                            + '<form>'
                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx">หมวดรายจ่าย</label>'
                                        + '<div class="col-md-8">'
                                            + '<select id="" name="" class="form-control input-sm" required>'
                                            + '</select>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'

                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx">ประเภท</label>'
                                        + '<div class="col-md-8">'
                                            + '<select id="" name="" class="form-control input-sm" required>'
                                            + '</select>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'

                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx">รายจ่ายจริง ปีงบประมาณที่ผ่านมา</label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">เงินนอกงบประมาณ</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">เงินงบประมาณ</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">รวมจ่าขจริง</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">รวมเงิน</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'

                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx">งบประมาณที่ได้รับการจัดสรรปีงบประมาณปัจจุบัน</label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">เงินนอกงบประมาณ</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">เงินงบประมาณ</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">รวมเงิน</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'

                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx">งบประมาณที่ได้รับการจัดสรรปีงบประมาณปัจจุบัน</label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">เงินนอกงบประมาณ</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">เงินงบประมาณ</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                        + '<div class="col-md-12" style="margin: 3px 0;">'
                                            + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                                            + '<div class="col-md-8">'
                                                + '<label class="col-md-4 control-label text-right" for="xxx">รวมเงิน</label>'
                                                + '<div class="col-md-8">'
                                                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                                                + '</div>'
                                            + '</div>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                        
                                + '<div class="form-group">'
                                    + '<div class="col-md-9">'
                                        + '<label class="col-md-4 control-label text-right" for="xxx">คำชี้แจง</label>'
                                        + '<div class="col-md-8">'
                                            + '<textarea id="" name="" class="form-control input-sm">'
                                            + '</textarea>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                                
                                + '<div class="col-md-12 text-right">'
                                    + '<button class="btn btn-primary"><i class="fa fa-plus-circle"></i> เพิ่ม</button>&nbsp;'
                                    + '<button class="btn btn-default"><i class="fa fa-trash"></i> ล้างข้อมูล</button>'
                                + '</div>'
                            + '</form>'
                        + '</div>'
                    + '</div>'
            + '</div>'
        + '</div>'
    + '</div>'

    + '<div id="bidderTable" class="col-md-12">'
        + '<table id="table" class="table table-bordered table-striped table-condensed mb-none">'
            + '<thead>'
                + '<tr>'
                    + '<th class="text-center" rowspan="2" style="vertical-align: middle;">ประเภท</th>'
                    + '<th class="text-center" colspan="4">รายจ่ายจริง ปีงบประมาณที่ผ่านมา (2557) (ณ 30 กันยายน)</th>'
                    + '<th class="text-center" colspan="3">งบประมาณที่ได้รับการจัดสรรปีงบประมาณปัจจุบัน (2558)</th>'
                    + '<th class="text-center" colspan="3">คำของบประมาณปีงบประมาณที่ขอตั้งงบประมาณ (2559)</th>'
                    + '<th class="text-center" rowspan="2" style="vertical-align: middle;">คำชี้แจง</th>'
                + '</tr>'
                + '<tr>'
                    + '<th class="text-center">เงินนอกงบประมาณ</th>'
                    + '<th class="text-center">เงินงบประมาณ</th>'
                    + '<th class="text-center">รายจ่ายจริง</th>'
                    + '<th class="text-center">รวมเงิน</th>'
                    + '<th class="text-center">เงินนอกงบประมาณ</th>'
                    + '<th class="text-center">เงินงบประมาณ</th>'
                    + '<th class="text-center">รวมเงิน</th>'
                    + '<th class="text-center">เงินนอกงบประมาณ</th>'
                    + '<th class="text-center">เงินงบประมาณ</th>'
                    + '<th class="text-center">รวมเงิน</th>'
                + '</tr>'

                + '<tr>'
                    + '<th class="text-center">รวมทั้งสิ้น</th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                    + '<th class="text-center"></th>'
                + '</tr>'
            + '</thead>'
            + '<tbody id="bidderBody">'
                + '<tr>'
                    + '<td colspan="12" class="text-center">-</td>'
                + '</tr>'
            + '</tbody>'
        + '</table>'
    + '</div>';
    
    $("#formBudget").html(html);
    
     
}