function buildingOneForm(){
    var html = '<div class="col-md-12 text-center">'
        + '<h4>'
            + 'คำชี้แจงรายละเอียดรายการก่อสร้าง และปรับปรุงสิ่งก่อสร้าง 1 ปี'
        + '</h4>'
    + '</div>'

    + '<form>'
        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">แผนงาน</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">ผลผลิต</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">รายการ</label>'
                + '<div class="col-md-8">'
                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">สถานที่ดำเนินการ</label>'
                + '<div class="col-md-8">'
                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">เหตุผลความจำเป็น</label>'
                + '<div class="col-md-8">'
                    + '<textarea id="" name="" class="form-control input-sm" required>'
                    + '</textarea>'
                + '</div>'
            + '</div>'
         + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">งบประมาณทั้งสิ้น</label>'
                + '<div class="col-md-8">'
                    + '<input type="text" id="" name="" class="form-control input-sm">'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">พื้นที่/ปริมาณงาน</label>'
                + '<div class="col-md-8">'
                    + '<input type="text" id="" name="" class="form-control input-sm">'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-12">'
                + '<label class="col-md-4 control-label text-right" for="xxx">ลักษณะการก่อสร้าง ปรับปรุง ขนาด และประมาณราคา</label>'
            + '</div>'
            + '<div class="col-md-12">'
                + '<table id="table" class="table table-bordered table-striped table-condensed mb-none">'
                    + '<thead>'
                        + '<tr>'
                            + '<th class="text-center">กิจกรรม/ดำเนินงาน</th>'
                            + '<th class="text-center">ขนาด/ปริมาณ</th>'
                            + '<th class="text-center">ราคาต่อหน่วย</th>'
                            + '<th class="text-center">เงิน</th>'
                        + '</tr>'
                    + '</thead>'
                    + '<tbody id="bidderBody">'
                        + '<tr>'
                            + '<td colspan="4" class="text-center">-</td>'
                        + '</tr>'
                    + '</tbody>'
                    + '<tfoot id="bidderBody">'
                        + '<tr>'
                            + '<td class="text-center">รวม</td>'
                            + '<td class="text-center"></td>'
                            + '<td class="text-center"></td>'
                            + '<td class="text-center"></td>'
                        + '</tr>'
                    + '</tfoot>'
                + '</table>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<div class="col-md-12" style="margin: 3px 0;">'
                    + '<label class="col-md-4 control-label text-right" for="xxx">แผนการดำเนินงาน</label>'
                    + '<div class="col-md-8">'
                        + '<label class="col-md-4 control-label text-right" for="xxx">ออกแบบ</label>'
                        + '<div class="col-md-8">'
                            + '<input type="text" id="" name="" class="form-control input-sm" required>'
                        + '</div>'
                    + '</div>'
                + '</div>'
                + '<div class="col-md-12" style="margin: 3px 0;">'
                    + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                    + '<div class="col-md-8">'
                        + '<label class="col-md-4 control-label text-right" for="xxx">ประกวดราคา</label>'
                        + '<div class="col-md-8">'
                            + '<input type="text" id="" name="" class="form-control input-sm" required>'
                        + '</div>'
                    + '</div>'
                + '</div>'
                + '<div class="col-md-12" style="margin: 3px 0;">'
                    + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                    + '<div class="col-md-8">'
                        + '<label class="col-md-4 control-label text-right" for="xxx">เซ็นสัญญา</label>'
                        + '<div class="col-md-8">'
                            + '<input type="text" id="" name="" class="form-control input-sm" required>'
                        + '</div>'
                    + '</div>'
                + '</div>'
                + '<div class="col-md-12" style="margin: 3px 0;">'
                    + '<label class="col-md-4 control-label text-right" for="xxx"></label>'
                    + '<div class="col-md-8">'
                        + '<label class="col-md-4 control-label text-right" for="xxx">ระยะเวลาการดำเนินการ</label>'
                        + '<div class="col-md-8">'
                            + '<input type="text" id="" name="" class="form-control input-sm" required>'
                        + '</div>'
                    + '</div>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="col-md-12 text-right">'
            + '<button class="btn btn-success"><i class="fa fa-save"></i> บันทึก</button>&nbsp;'
            + '<button class="btn btn-default"><i class="fa fa-trash"></i> ล้างข้อมูล</button>'
        + '</div>'
    + '</form>';
    
    $("#formBudget").html(html);

}