function buildingOneForm(){
    var html = '<div class="col-md-12 text-center">'
        + '<h4>'
            + 'คำชี้แจงรายละเอียดรายการก่อสร้าง และปรับปรุงสิ่งก่อสร้าง 1 ปี'
        + '</h4>'
    + '</div>'

    + '<form>'
        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">หมวดรายจ่าย</label>'
                + '<div class="col-md-8">'
                    + '<select id="" name="" class="form-control input-sm" required>'
                    + '</select>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">ชื่อตำแหน่งอัตราเดิม</label>'
                + '<div class="col-md-8">'
                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">ระดับ</label>'
                + '<div class="col-md-8">'
                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">อัตราเงินเดือน</label>'
                + '<div class="col-md-8">'
                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">จำนวนอัตรา</label>'
                + '<div class="col-md-4">'
                    + '<label class="col-md-6 control-label text-right" for="xxx">มีคนครอง</label>'
                    + '<div class="col-md-6">'
                        + '<input type="text" id="" name="" class="form-control input-sm" required>'
                    + '</div>'
                + '</div>'
                + '<div class="col-md-4">'
                    + '<label class="col-md-6 control-label text-right" for="xxx">อัตราว่าง</label>'
                    + '<div class="col-md-6">'
                        + '<input type="text" id="" name="" class="form-control input-sm" required>'
                    + '</div>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">จำนวนเงินทั้งปี</label>'
                + '<div class="col-md-8">'
                    + '<input type="text" id="" name="" class="form-control input-sm" required>'
                + '</div>'
            + '</div>'
         + '</div>'

        + '<div class="form-group">'
            + '<div class="col-md-9">'
                + '<label class="col-md-4 control-label text-right" for="xxx">คำชี้แจง</label>'
                + '<div class="col-md-8">'
                    + '<textarea id="" name="" class="form-control input-sm">'
                    + '</textarea>'
                + '</div>'
            + '</div>'
        + '</div>'

        + '<div class="col-md-12 text-right">'
            + '<button class="btn btn-primary"><i class="fa fa-plus-circle"></i> เพิ่ม</button>&nbsp;'
            + '<button class="btn btn-default"><i class="fa fa-trash"></i> ยกเลิก</button>'
        + '</div>'
    + '</form>';
    
    $("#formBudget").html(html);

}